More works on docker compose model
uc-group/daffy pull request #12
Opened 2018-11-23 22:30 UTC by pgoca

2018-11-24 07:21 UTC, gbalcewicz requested changes

2018-11-24 07:21 UTC, gbalcewicz commented on src/Model/DockerCompose/Service.php
> +    public function __construct(ServiceBuilder $serviceBuilder)
I think the dependency went in wrong direction. Entity should never depend on the builder.

2018-11-24 07:21 UTC, gbalcewicz commented on src/Model/DockerCompose/Service.php
> +        $shortSyntax = true;
I don't think we have to care about both cases. Short if for humanz so if we don't write it by hand let's pick the recommended one from docs. If there is no favorite, pick one, there is no point in complicating such things.

2018-11-24 07:21 UTC, gbalcewicz commented on src/Model/DockerCompose/Service/Build.php
> +    public function __construct(string $context, string $dockerfile = "", array $args = [])
Not a big fan of empty strings. Can we make it nullable?

2018-11-24 07:21 UTC, gbalcewicz commented on src/Model/DockerCompose/Service/ServiceElementInterface.php
> +    public function getData(): array;
Is there any benefit for this? I think it should have concrete methods and in the yaml builder it should use it instead of so generic getData.

2018-11-24 07:21 UTC, gbalcewicz commented on src/Model/DockerCompose/ServiceBuilder.php
> +        if (empty($this->dns)) {
You could always keep the dns as array so you won't complicate it so much. The conversion to yaml should bother how to display it.

2018-11-24 07:21 UTC, gbalcewicz commented on src/Model/DockerCompose/ServiceBuilder.php
> +class ServiceBuilder
This class don't look like a builder. Builders collect data and when ready executes building process returning instance what is builder of.

2018-11-26 17:24 UTC, pgoca commented on src/Model/DockerCompose/Service/Build.php
> +    public function __construct(string $context, string $dockerfile = "", array $args = [])
Sure

2018-11-26 17:25 UTC, pgoca commented on src/Model/DockerCompose/ServiceBuilder.php
> +        if (empty($this->dns)) {
oki doki

2018-11-26 17:29 UTC, pgoca commented on src/Model/DockerCompose/Service.php
> +        $shortSyntax = true;
Sure, we can stick to the shorter version for now.

2018-11-26 17:51 UTC, pgoca commented
@gbalcewicz I've change the implementation a little bit, could you please review it?

2018-11-26 18:00 UTC, gbalcewicz commented
@pgoca nice work, some nitpicks, but it can be change later. I'll merge it.

2018-11-26 18:00 UTC, merged